# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o /app/tmp/main ."
  bin = "/app/tmp/main"
  exclude_dir = ["tmp", "vendor", ".git"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
