version: '3.8'

services:
  # db:
  #   image: postgres:14.14
  #   environment:
  #     POSTGRES_DB: yourdbname
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "8080:8080"
#     environment:
#       - DB_HOST=db
#       - DB_USER=youruser
#       - DB_PASSWORD=yourpassword
#       - DB_NAME=yourdbname
#     depends_on:
#       - db

# volumes:
#   pgdata:

