# fly.toml app configuration file generated for vote-dapp-backend on 2023-11-04T20:20:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vote-dapp-backend"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
